spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collagedb
    username: root
    password: aman yadav
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: amany49751@gmail.com
    password: cckr ddab gkbt pqkv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt-secret-key: NbIfb2S2K3ysIv2QO4IugWbuu-3m_BRd1IVJlaiBiRM