spring:
  datasource:
    url: jdbc:mysql://college-database-college-management.h.aivencloud.com:13625/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: avnadmin
    password: AVNS_oxOk_uSPgpUaNag75AI

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: amany49751@gmail.com
    password: cckr ddab gkbt pqkv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8000

jwt-secret-key: NbIfb2S2K3ysIv2QO4IugWbuu-3m_BRd1IVJlaiBiRM